
export const categories = [
  { id: 1, name: { pt: "Grãos", en: "Grains", es: "Granos" } },
  { id: 2, name: { pt: "Carnes", en: "Meat", es: "Carnes" } },
  { id: 3, name: { pt: "Laticínios", en: "Dairy", es: "Lácteos" } },
  { id: 4, name: { pt: "Hortifruti", en: "Produce", es: "Frutas y Verduras" } },
  { id: 5, name: { pt: "Bebidas", en: "Beverages", es: "Bebidas" } },
  { id: 6, name: { pt: "Padaria", en: "Bakery", es: "Panadería" } },
  { id: 7, name: { pt: "Higiene", en: "Personal Care", es: "Higiene" } },
  { id: 8, name: { pt: "Limpeza", en: "Cleaning", es: "Limpieza" } },
  { id: 9, name: { pt: "Congelados", en: "Frozen", es: "Congelados" } },
  { id: 10, name: { pt: "Doces", en: "Sweets", es: "Dulces" } },
  { id: 11, name: { pt: "Massas", en: "Pasta", es: "Pastas" } },
  { id: 12, name: { pt: "Molhos e Temperos", en: "Sauces and Seasonings", es: "Salsas y Condimentos" } },
  { id: 13, name: { pt: "Pet Shop", en: "Pet Supplies", es: "Artículos para Mascotas" } },
  { id: 14, name: { pt: "Utilidades Domésticas", en: "Household Items", es: "Artículos del Hogar" } },
  { id: 15, name: { pt: "Bebê", en: "Baby", es: "Bebé" } },
  { id: 16, name: { pt: "Cereais", en: "Cereals", es: "Cereales" } },
  { id: 17, name: { pt: "Snacks", en: "Snacks", es: "Snacks" } },
  { id: 18, name: { pt: "Enlatados", en: "Canned Goods", es: "Enlatados" } },
  { id: 19, name: { pt: "Óleos e Gorduras", en: "Oils and Fats", es: "Aceites y Grasas" } },
  { id: 20, name: { pt: "Produtos Naturais", en: "Natural Products", es: "Productos Naturales" } }
]

export const items = [
  // Grãos (ID 1)
  { name: { pt: "Arroz", en: "Rice", es: "Arroz" }, categoryId: 1 },
  { name: { pt: "Feijão", en: "Beans", es: "Frijoles" }, categoryId: 1 },
  { name: { pt: "Lentilha", en: "Lentils", es: "Lentejas" }, categoryId: 1 },
  { name: { pt: "Grão-de-bico", en: "Chickpeas", es: "Garbanzos" }, categoryId: 1 },
  { name: { pt: "Ervilha", en: "Peas", es: "Guisantes" }, categoryId: 1 },
  { name: { pt: 'Farinha de trigo', en: 'Wheat flour', es: 'Harina de trigo' }, categoryId: 1 },
  { name: { pt: 'Açúcar', en: 'Sugar', es: 'Azúcar' }, categoryId: 1 },
  { name: { pt: 'Fermento químico', en: 'Baking powder', es: 'Levadura química' }, categoryId: 1 },

  // Carnes (ID 2)
  { name: { pt: "Picanha", en: "Picanha", es: "Picaña" }, categoryId: 2 },
  { name: { pt: "Contrafilé", en: "Sirloin", es: "Contrafilete" }, categoryId: 2 },
  { name: { pt: "Alcatra", en: "Rump", es: "Cadera" }, categoryId: 2 },
  { name: { pt: "Maminha", en: "Bottom Sirloin", es: "Punta de anca" }, categoryId: 2 },
  { name: { pt: "Coxão mole", en: "Top Round", es: "Tapa de cuadril" }, categoryId: 2 },
  { name: { pt: "Coxão duro", en: "Bottom Round", es: "Bola de lomo" }, categoryId: 2 },
  { name: { pt: "Patinho", en: "Knuckle", es: "Pata" }, categoryId: 2 },
  { name: { pt: "Acém", en: "Chuck", es: "Aguja" }, categoryId: 2 },
  { name: { pt: "Paleta", en: "Shoulder", es: "Paleta" }, categoryId: 2 },
  { name: { pt: "Peito de frango", en: "Chicken breast", es: "Pechuga de pollo" }, categoryId: 2 },
  { name: { pt: "Coxa de frango", en: "Chicken thigh", es: "Muslo de pollo" }, categoryId: 2 },
  { name: { pt: "Sobrecoxa de frango", en: "Chicken drumstick", es: "Contramuslo de pollo" }, categoryId: 2 },
  { name: { pt: "Asa de frango", en: "Chicken wing", es: "Ala de pollo" }, categoryId: 2 },
  { name: { pt: "Carne moída", en: "Ground beef", es: "Carne molida" }, categoryId: 2 },
  { name: { pt: "Costela bovina", en: "Beef ribs", es: "Costilla de res" }, categoryId: 2 },
  { name: { pt: "Costela suína", en: "Pork ribs", es: "Costilla de cerdo" }, categoryId: 2 },
  { name: { pt: "Bisteca suína", en: "Pork chop", es: "Chuleta de cerdo" }, categoryId: 2 },
  { name: { pt: "Linguiça toscana", en: "Tuscan sausage", es: "Salchicha toscana" }, categoryId: 2 },
  { name: { pt: "Linguiça calabresa", en: "Calabrese sausage", es: "Salchicha calabresa" }, categoryId: 2 },
  { name: { pt: "Linguiça de frango", en: "Chicken sausage", es: "Salchicha de pollo" }, categoryId: 2 },
  { name: { pt: "Linguiça de porco", en: "Pork sausage", es: "Salchicha de cerdo" }, categoryId: 2 },
  { name: { pt: "Bacon", en: "Bacon", es: "Tocino" }, categoryId: 2 },
  { name: { pt: "Presunto cru", en: "Prosciutto", es: "Jamón crudo" }, categoryId: 2 },
  { name: { pt: "Peito de peru", en: "Turkey breast", es: "Pechuga de pavo" }, categoryId: 2 },
  { name: { pt: "Salsicha", en: "Sausage", es: "Salchicha" }, categoryId: 2 },
  { name: { pt: "Mortadela", en: "Mortadella", es: "Mortadela" }, categoryId: 2 },
  { name: { pt: "Salame", en: "Salami", es: "Salami" }, categoryId: 2 },
  { name: { pt: "Ovos", en: "Eggs", es: "Huevos" }, categoryId: 2 },
  { name: { pt: "Ovos de codorna", en: "Quail eggs", es: "Huevos de codorniz" }, categoryId: 2 },
  { name: { pt: "Filé de tilápia", en: "Tilapia fillet", es: "Filete de tilapia" }, categoryId: 2 },
  { name: { pt: "Filé de merluza", en: "Hake fillet", es: "Filete de merluza" }, categoryId: 2 },
  { name: { pt: "Sardinha fresca", en: "Fresh sardine", es: "Sardina fresca" }, categoryId: 2 },
  { name: { pt: "Atum fresco", en: "Fresh tuna", es: "Atún fresco" }, categoryId: 2 },
  { name: { pt: "Camarão", en: "Shrimp", es: "Camarón" }, categoryId: 2 },

  // Laticínios (ID 3)
  { name: { pt: "Leite", en: "Milk", es: "Leche" }, categoryId: 3 },
  { name: { pt: "Queijo", en: "Cheese", es: "Queso" }, categoryId: 3 },
  { name: { pt: "Cream cheese", en: "Cream cheese", es: "Queso crema" }, categoryId: 3 },
  { name: { pt: "Ricota", en: "Ricotta", es: "Ricotta" }, categoryId: 3 },
  { name: { pt: "Queijo ralado", en: "Grated cheese", es: "Queso rallado" }, categoryId: 3 },
  { name: { pt: "Queijo minas", en: "Minas cheese", es: "Queso minas" }, categoryId: 3 },
  { name: { pt: "Queijo prato", en: "Prato cheese", es: "Queso prato" }, categoryId: 3 },
  { name: { pt: "Iogurte", en: "Yogurt", es: "Yogur" }, categoryId: 3 },
  { name: { pt: "Manteiga", en: "Butter", es: "Mantequilla" }, categoryId: 3 },
  { name: { pt: "Requeijão", en: "Creamy cheese", es: "Requesón" }, categoryId: 3 },

  // Hortifruti (ID 4)
  { name: { pt: "Banana", en: "Banana", es: "Plátano" }, categoryId: 4 },
  { name: { pt: "Maçã", en: "Apple", es: "Manzana" }, categoryId: 4 },
  { name: { pt: "Tomate", en: "Tomato", es: "Tomate" }, categoryId: 4 },
  { name: { pt: "Cenoura", en: "Carrot", es: "Zanahoria" }, categoryId: 4 },
  { name: { pt: "Alface", en: "Lettuce", es: "Lechuga" }, categoryId: 4 },
  { name: { pt: "Abacate", en: "Avocado", es: "Aguacate" }, categoryId: 4 },
  { name: { pt: "Abacaxi", en: "Pineapple", es: "Piña" }, categoryId: 4 },
  { name: { pt: "Acerola", en: "Acerola", es: "Acerola" }, categoryId: 4 },
  { name: { pt: "Ameixa", en: "Plum", es: "Ciruela" }, categoryId: 4 },
  { name: { pt: "Amora", en: "Blackberry", es: "Mora" }, categoryId: 4 },
  { name: { pt: "Caju", en: "Cashew", es: "Marañón" }, categoryId: 4 },
  { name: { pt: "Caqui", en: "Persimmon", es: "Caqui" }, categoryId: 4 },
  { name: { pt: "Carambola", en: "Star fruit", es: "Carambola" }, categoryId: 4 },
  { name: { pt: "Coco", en: "Coconut", es: "Coco" }, categoryId: 4 },
  { name: { pt: "Damasco", en: "Apricot", es: "Albaricoque" }, categoryId: 4 },
  { name: { pt: "Figo", en: "Fig", es: "Higo" }, categoryId: 4 },
  { name: { pt: "Framboesa", en: "Raspberry", es: "Frambuesa" }, categoryId: 4 },
  { name: { pt: "Goiaba", en: "Guava", es: "Guayaba" }, categoryId: 4 },
  { name: { pt: "Jabuticaba", en: "Jabuticaba", es: "Jabuticaba" }, categoryId: 4 },
  { name: { pt: "Jaca", en: "Jackfruit", es: "Yaca" }, categoryId: 4 },
  { name: { pt: "Kiwi", en: "Kiwi", es: "Kiwi" }, categoryId: 4 },
  { name: { pt: "Laranja", en: "Orange", es: "Naranja" }, categoryId: 4 },
  { name: { pt: "Limão", en: "Lemon", es: "Limón" }, categoryId: 4 },
  { name: { pt: "Lima", en: "Lime", es: "Lima" }, categoryId: 4 },
  { name: { pt: "Mamão", en: "Papaya", es: "Papaya" }, categoryId: 4 },
  { name: { pt: "Manga", en: "Mango", es: "Mango" }, categoryId: 4 },
  { name: { pt: 'Maracujá', en: 'Passion fruit', es: 'Maracuyá' }, categoryId: 4 },
  { name: { pt: 'Melancia', en: 'Watermelon', es: 'Sandía' }, categoryId: 4 },
  { name: { pt: 'Melão', en: 'Melon', es: 'Melón' }, categoryId: 4 },
  { name: { pt: 'Mexerica', en: 'Mandarin', es: 'Mandarina' }, categoryId: 4 },
  { name: { pt: 'Morango', en: 'Strawberry', es: 'Fresa' }, categoryId: 4 },
  { name: { pt: 'Nectarina', en: 'Nectarine', es: 'Nectarina' }, categoryId: 4 },
  { name: { pt: 'Pêra', en: 'Pear', es: 'Pera' }, categoryId: 4 },
  { name: { pt: 'Pêssego', en: 'Peach', es: 'Durazno' }, categoryId: 4 },
  { name: { pt: 'Pitanga', en: 'Brazilian cherry', es: 'Cereza de Surinam' }, categoryId: 4 },
  { name: { pt: 'Pitaya', en: 'Dragon fruit', es: 'Pitahaya' }, categoryId: 4 },
  { name: { pt: 'Romã', en: 'Pomegranate', es: 'Granada' }, categoryId: 4 },
  { name: { pt: 'Tamarindo', en: 'Tamarind', es: 'Tamarindo' }, categoryId: 4 },
  { name: { pt: 'Tangerina', en: 'Tangerine', es: 'Mandarina' }, categoryId: 4 },
  { name: { pt: 'Uva', en: 'Grape', es: 'Uva' }, categoryId: 4 },
  { name: { pt: 'Uva passa', en: 'Raisin', es: 'Uva pasa' }, categoryId: 4 },
  { name: { pt: 'Acerola', en: 'Acerola', es: 'Acerola' }, categoryId: 4 },
  { name: { pt: 'Cupuaçu', en: 'Cupuaçu', es: 'Cupuaçu' }, categoryId: 4 },
  { name: { pt: 'Graviola', en: 'Soursop', es: 'Guanábana' }, categoryId: 4 },
  { name: { pt: 'Guaraná', en: 'Guarana', es: 'Guaraná' }, categoryId: 4 },
  { name: { pt: 'Pupunha', en: 'Peach palm', es: 'Chontaduro' }, categoryId: 4 },
  { name: { pt: 'Sapoti', en: 'Sapodilla', es: 'Zapote' }, categoryId: 4 },
  { name: { pt: 'Seriguela', en: 'Spanish plum', es: 'Ciruela' }, categoryId: 4 },

  // Bebidas (ID 5)
  { name: { pt: 'Refrigerante', en: 'Soda', es: 'Refresco' }, categoryId: 5 },
  { name: { pt: 'Suco', en: 'Juice', es: 'Jugo' }, categoryId: 5 },
  { name: { pt: 'Água mineral', en: 'Mineral water', es: 'Agua mineral' }, categoryId: 5 },
  { name: { pt: 'Cerveja', en: 'Beer', es: 'Cerveza' }, categoryId: 5 },
  { name: { pt: 'Vinho', en: 'Wine', es: 'Vino' }, categoryId: 5 },
  { name: { pt: 'Energético', en: 'Energy drink', es: 'Bebida energética' }, categoryId: 5 },
  { name: { pt: 'Água com gás', en: 'Sparkling water', es: 'Agua con gas' }, categoryId: 5 },
  { name: { pt: 'Cerveja artesanal', en: 'Craft beer', es: 'Cerveza artesanal' }, categoryId: 5 },
  { name: { pt: 'Refrigerante zero', en: 'Diet soda', es: 'Refresco sin azúcar' }, categoryId: 5 },
  { name: { pt: 'Água saborizada', en: 'Flavored water', es: 'Agua saborizada' }, categoryId: 5 },
  { name: { pt: 'Café', en: 'Coffee', es: 'Café' }, categoryId: 5 },
  { name: { pt: 'Chá', en: 'Tea', es: 'Té' }, categoryId: 5 },

  // Padaria (ID 6)
  { name: { pt: 'Pão francês', en: 'French bread', es: 'Pan francés' }, categoryId: 6 },
  { name: { pt: 'Pão de forma', en: 'Sliced bread', es: 'Pan de molde' }, categoryId: 6 },
  { name: { pt: 'Bolo', en: 'Cake', es: 'Pastel' }, categoryId: 6 },
  { name: { pt: 'Croissant', en: 'Croissant', es: 'Cruasán' }, categoryId: 6 },
  { name: { pt: 'Torrada', en: 'Toast', es: 'Tostada' }, categoryId: 6 },
  { name: { pt: 'Pão integral', en: 'Whole wheat bread', es: 'Pan integral' }, categoryId: 6 },
  { name: { pt: 'Pão de centeio', en: 'Rye bread', es: 'Pan de centeno' }, categoryId: 6 },
  { name: { pt: 'Pão de queijo congelado', en: 'Frozen cheese bread', es: 'Pan de queso congelado' }, categoryId: 6 },
  { name: { pt: 'Biscoito de polvilho', en: 'Cassava starch biscuit', es: 'Galleta de almidón de yuca' }, categoryId: 6 },
  { name: { pt: 'Rosca doce', en: 'Sweet roll', es: 'Rosca dulce' }, categoryId: 6 },

  // Higiene (ID 7)
  { name: { pt: 'Sabonete', en: 'Soap', es: 'Jabón' }, categoryId: 7 },
  { name: { pt: 'Shampoo', en: 'Shampoo', es: 'Champú' }, categoryId: 7 },
  { name: { pt: 'Condicionador', en: 'Conditioner', es: 'Acondicionador' }, categoryId: 7 },
  { name: { pt: 'Pasta de dente', en: 'Toothpaste', es: 'Pasta dental' }, categoryId: 7 },
  { name: { pt: 'Desodorante', en: 'Deodorant', es: 'Desodorante' }, categoryId: 7 },
  { name: { pt: 'Barbeador descartável', en: 'Disposable razor', es: 'Afeitadora desechable' }, categoryId: 7 },
  { name: { pt: 'Hidratante corporal', en: 'Body lotion', es: 'Crema corporal' }, categoryId: 7 },
  { name: { pt: 'Protetor solar', en: 'Sunscreen', es: 'Protector solar' }, categoryId: 7 },
  { name: { pt: 'Creme para as mãos', en: 'Hand cream', es: 'Crema de manos' }, categoryId: 7 },
  { name: { pt: 'Lenço facial', en: 'Facial tissue', es: 'Pañuelo facial' }, categoryId: 7 },
  { name: { pt: 'Papel higiênico', en: 'Toilet paper', es: 'Papel higiénico' }, categoryId: 7 },
  { name: { pt: 'Papel toalha', en: 'Paper towel', es: 'Papel de cocina' }, categoryId: 7 },
  { name: { pt: 'Guardanapo', en: 'Napkin', es: 'Servilleta' }, categoryId: 7 },
  { name: { pt: 'Lenço de papel', en: 'Tissue paper', es: 'Pañuelo de papel' }, categoryId: 7 },
  { name: { pt: 'Absorvente', en: 'Sanitary pad', es: 'Toalla sanitaria' }, categoryId: 7 },
 
  // Limpeza (ID 8)
  { name: { pt: 'Detergente', en: 'Detergent', es: 'Detergente' }, categoryId: 8 },
  { name: { pt: 'Sabão em pó', en: 'Laundry powder', es: 'Jabón en polvo' }, categoryId: 8 },
  { name: { pt: 'Amaciante', en: 'Fabric softener', es: 'Suavizante' }, categoryId: 8 },
  { name: { pt: 'Água sanitária', en: 'Bleach', es: 'Lejía' }, categoryId: 8 },
  { name: { pt: 'Esponja', en: 'Sponge', es: 'Esponja' }, categoryId: 8 },
  { name: { pt: 'Sabão em pedra', en: 'Bar soap', es: 'Jabón en barra' }, categoryId: 8 },
  { name: { pt: 'Luvas de borracha', en: 'Rubber gloves', es: 'Guantes de goma' }, categoryId: 8 },
  { name: { pt: 'Saco organizador de lixo', en: 'Trash organizer bag', es: 'Bolsa organizadora de basura' }, categoryId: 8 },
  { name: { pt: 'Escova de limpeza', en: 'Cleaning brush', es: 'Cepillo de limpieza' }, categoryId: 8 },
  { name: { pt: 'Pano de microfibra', en: 'Microfiber cloth', es: 'Paño de microfibra' }, categoryId: 8 },

  // Congelados (ID 9)
  { name: { pt: 'Pizza congelada', en: 'Frozen pizza', es: 'Pizza congelada' }, categoryId: 9 },
  { name: { pt: 'Lasanha congelada', en: 'Frozen lasagna', es: 'Lasaña congelada' }, categoryId: 9 },
  { name: { pt: 'Legumes congelados', en: 'Frozen vegetables', es: 'Verduras congeladas' }, categoryId: 9 },
  { name: { pt: 'Frango empanado', en: 'Breaded chicken', es: 'Pollo empanizado' }, categoryId: 9 },
  { name: { pt: 'Sorvete', en: 'Ice cream', es: 'Helado' }, categoryId: 9 },

  //
  { name: { pt: 'Chocolate', en: 'Chocolate', es: 'Chocolate' }, categoryId: 10 },
  { name: { pt: 'Bala', en: 'Candy', es: 'Caramelo' }, categoryId: 10 },
  { name: { pt: 'Biscoito recheado', en: 'Stuffed cookie', es: 'Galleta rellena' }, categoryId: 10 },
  { name: { pt: 'Goiabada', en: 'Guava paste', es: 'Dulce de guayaba' }, categoryId: 10 },
  { name: { pt: 'Doce de leite', en: 'Milk caramel', es: 'Dulce de leche' }, categoryId: 10 },
  { name: { pt: 'Paçoca', en: 'Peanut candy', es: 'Dulce de maní' }, categoryId: 10 },
  { name: { pt: 'Pé de moleque', en: 'Peanut brittle', es: 'Turrón de maní' }, categoryId: 10 },
  { name: { pt: 'Rapadura', en: 'Raw cane sugar', es: 'Panela' }, categoryId: 10 },
  { name: { pt: 'Brigadeiro', en: 'Brigadeiro', es: 'Brigadeiro' }, categoryId: 10 },
  { name: { pt: 'Cocada', en: 'Coconut sweet', es: 'Cocada' }, categoryId: 10 },
  { name: { pt: 'Chocolate em pó', en: 'Cocoa powder', es: 'Cacao en polvo' }, categoryId: 10 },
  { name: { pt: 'Leite condensado', en: 'Condensed milk', es: 'Leche condensada' }, categoryId: 10 },


  //
  { name: { pt: 'Macarrão', en: 'Pasta', es: 'Pasta' }, categoryId: 11 },
  { name: { pt: 'Lasanha', en: 'Lasagna', es: 'Lasaña' }, categoryId: 11 },
  { name: { pt: 'Espaguete', en: 'Spaghetti', es: 'Espagueti' }, categoryId: 11 },
  { name: { pt: 'Talharim', en: 'Tagliatelle', es: 'Tallarines' }, categoryId: 11 },
  { name: { pt: 'Nhoque', en: 'Gnocchi', es: 'Ñoquis' }, categoryId: 11 },

  //
  { name: { pt: 'Molho de tomate', en: 'Tomato sauce', es: 'Salsa de tomate' }, categoryId: 12 },
  { name: { pt: 'Ketchup', en: 'Ketchup', es: 'Ketchup' }, categoryId: 12 },
  { name: { pt: 'Mostarda', en: 'Mustard', es: 'Mostaza' }, categoryId: 12 },
  { name: { pt: 'Maionese', en: 'Mayonnaise', es: 'Mayonesa' }, categoryId: 12 },
  { name: { pt: 'Sal', en: 'Salt', es: 'Sal' }, categoryId: 12 },
  { name: { pt: 'Vinagre', en: 'Vinegar', es: 'Vinagre' }, categoryId: 12 },
  { name: { pt: 'Molho shoyu', en: 'Soy sauce', es: 'Salsa de soya' }, categoryId: 12 },
  { name: { pt: 'Molho inglês', en: 'Worcestershire sauce', es: 'Salsa inglesa' }, categoryId: 12 },
  { name: { pt: 'Pimenta', en: 'Pepper', es: 'Pimienta' }, categoryId: 12 },
  { name: { pt: 'Tempero pronto', en: 'Pre-made seasoning', es: 'Condimento preparado' }, categoryId: 12 },

  //
  { name: { pt: 'Ração para cachorro', en: 'Dog food', es: 'Comida para perro' }, categoryId: 13 },
  { name: { pt: 'Ração para gato', en: 'Cat food', es: 'Comida para gato' }, categoryId: 13 },
  { name: { pt: 'Areia sanitária', en: 'Cat litter', es: 'Arena sanitaria' }, categoryId: 13 },
  { name: { pt: 'Petisco para cachorro', en: 'Dog treat', es: 'Golosina para perro' }, categoryId: 13 },
  { name: { pt: 'Coleira', en: 'Collar', es: 'Collar' }, categoryId: 13 },
  { name: { pt: 'Brinquedo para pets', en: 'Pet toy', es: 'Juguete para mascotas' }, categoryId: 13 },
  { name: { pt: 'Tapete higiênico', en: 'Pee pad', es: 'Alfombrilla higiénica' }, categoryId: 13 },
  { name: { pt: 'Shampoo para pets', en: 'Pet shampoo', es: 'Champú para mascotas' }, categoryId: 13 },
  { name: { pt: 'Osso artificial', en: 'Chew bone', es: 'Hueso artificial' }, categoryId: 13 },
  { name: { pt: 'Arranhador para gatos', en: 'Cat scratcher', es: 'Rascador para gatos' }, categoryId: 13 },

  //
  { name: { pt: 'Papel alumínio', en: 'Aluminum foil', es: 'Papel de aluminio' }, categoryId: 14 },
  { name: { pt: 'Papel manteiga', en: 'Parchment paper', es: 'Papel para hornear' }, categoryId: 14 },
  { name: { pt: 'Saco plástico', en: 'Plastic bag', es: 'Bolsa plástica' }, categoryId: 14 },
  { name: { pt: 'Filtro de café', en: 'Coffee filter', es: 'Filtro de café' }, categoryId: 14 },
  { name: { pt: 'Vasilha plástica', en: 'Plastic container', es: 'Recipiente plástico' }, categoryId: 14 },

  //
  { name: { pt: 'Fralda descartável', en: 'Disposable diaper', es: 'Pañal desechable' }, categoryId: 15 },
  { name: { pt: 'Lenço umedecido', en: 'Wet wipes', es: 'Toallitas húmedas' }, categoryId: 15 },
  { name: { pt: 'Pomada para assaduras', en: 'Diaper rash cream', es: 'Pomada para rozaduras' }, categoryId: 15 },
  { name: { pt: 'Mamadeira', en: 'Baby bottle', es: 'Biberón' }, categoryId: 15 },
  { name: { pt: 'Chupeta', en: 'Pacifier', es: 'Chupete' }, categoryId: 15 },

  //
  { name: { pt: 'Cereal matinal', en: 'Breakfast cereal', es: 'Cereal matutino' }, categoryId: 16 },
  { name: { pt: 'Aveia', en: 'Oats', es: 'Avena' }, categoryId: 16 },
  { name: { pt: 'Granola', en: 'Granola', es: 'Granola' }, categoryId: 16 },
  { name: { pt: 'Farinha de milho', en: 'Corn flour', es: 'Harina de maíz' }, categoryId: 16 },
  { name: { pt: 'Mingau', en: 'Porridge', es: 'Gachas' }, categoryId: 16 },

  //
  { name: { pt: 'Batata chips', en: 'Potato chips', es: 'Papas fritas' }, categoryId: 17 },
  { name: { pt: 'Amendoim', en: 'Peanut', es: 'Maní' }, categoryId: 17 },
  { name: { pt: 'Pipoca', en: 'Popcorn', es: 'Palomitas' }, categoryId: 17 },
  { name: { pt: 'Torradinha', en: 'Crouton', es: 'Tostadita' }, categoryId: 17 },
  { name: { pt: 'Biscoito salgado', en: 'Salt cracker', es: 'Galleta salada' }, categoryId: 17 },

  //
  { name: { pt: 'Milho verde enlatado', en: 'Canned corn', es: 'Maíz enlatado' }, categoryId: 18 },
  { name: { pt: 'Ervilha enlatada', en: 'Canned peas', es: 'Guisantes enlatados' }, categoryId: 18 },
  { name: { pt: 'Atum enlatado', en: 'Canned tuna', es: 'Atún enlatado' }, categoryId: 18 },
  { name: { pt: 'Sardinha enlatada', en: 'Canned sardines', es: 'Sardinas enlatadas' }, categoryId: 18 },
  { name: { pt: 'Molho pronto enlatado', en: 'Canned sauce', es: 'Salsa enlatada' }, categoryId: 18 },

  //
  { name: { pt: 'Óleo de soja', en: 'Soybean oil', es: 'Aceite de soya' }, categoryId: 19 },
  { name: { pt: 'Azeite de oliva', en: 'Olive oil', es: 'Aceite de oliva' }, categoryId: 19 },
  { name: { pt: 'Óleo de girassol', en: 'Sunflower oil', es: 'Aceite de girasol' }, categoryId: 19 },
  { name: { pt: 'Banha', en: 'Lard', es: 'Manteca' }, categoryId: 19 },
  { name: { pt: 'Margarina', en: 'Margarine', es: 'Margarina' }, categoryId: 19 },

  //
  { name: { pt: 'Castanha-do-pará', en: 'Brazil nut', es: 'Nuez de Brasil' }, categoryId: 20 },
  { name: { pt: 'Castanha de caju', en: 'Cashew nut', es: 'Anacardo' }, categoryId: 20 },
  { name: { pt: 'Nozes', en: 'Walnuts', es: 'Nueces' }, categoryId: 20 },
  { name: { pt: 'Amêndoas', en: 'Almonds', es: 'Almendras' }, categoryId: 20 },
  { name: { pt: 'Sementes de chia', en: 'Chia seeds', es: 'Semillas de chía' }, categoryId: 20 },
  { name: { pt: 'Sementes de linhaça', en: 'Flax seeds', es: 'Semillas de lino' }, categoryId: 20 },

  //
  
  { name: 'Abóbora', categoryId: 4 },
  { name: 'Abobrinha', categoryId: 4 },
  { name: 'Agrião', categoryId: 4 },
  { name: 'Aipo', categoryId: 4 },
  { name: 'Alcachofra', categoryId: 4 },
  { name: 'Alho', categoryId: 4 },
  { name: 'Alho-poró', categoryId: 4 },
  { name: 'Aspargo', categoryId: 4 },
  { name: 'Batata', categoryId: 4 },
  { name: 'Batata doce', categoryId: 4 },
  { name: 'Batata baroa', categoryId: 4 },
  { name: 'Berinjela', categoryId: 4 },
  { name: 'Beterraba', categoryId: 4 },
  { name: 'Brócolis', categoryId: 4 },
  { name: 'Cebola', categoryId: 4 },
  { name: 'Cebolinha', categoryId: 4 },
  { name: 'Chicória', categoryId: 4 },
  { name: 'Coentro', categoryId: 4 },
  { name: 'Couve', categoryId: 4 },
  { name: 'Couve flor', categoryId: 4 },
  { name: 'Couve de bruxelas', categoryId: 4 },
  { name: 'Espinafre', categoryId: 4 },
  { name: 'Erva-doce', categoryId: 4 },
  { name: 'Escarola', categoryId: 4 },
  { name: 'Funcho', categoryId: 4 },
  { name: 'Gengibre', categoryId: 4 },
  { name: 'Inhame', categoryId: 4 },
  { name: 'Jiló', categoryId: 4 },
  { name: 'Maxixe', categoryId: 4 },
  { name: 'Mostarda', categoryId: 4 },
  { name: 'Nabo', categoryId: 4 },
  { name: 'Palmito', categoryId: 4 },
  { name: 'Pepino', categoryId: 4 },
  { name: 'Pimentão', categoryId: 4 },
  { name: 'Quiabo', categoryId: 4 },
  { name: 'Rabanete', categoryId: 4 },
  { name: 'Repolho', categoryId: 4 },
  { name: 'Rúcula', categoryId: 4 },
  { name: 'Salsa', categoryId: 4 },
  { name: 'Taioba', categoryId: 4 },
  { name: 'Vagem', categoryId: 4 },
  { name: 'Xuxu', categoryId: 4 },
  { name: 'Mandioquinha', categoryId: 4 },
  { name: 'Bardana', categoryId: 4 },
  { name: 'Cará', categoryId: 4 },
  { name: 'Chuchu', categoryId: 4 },
  { name: 'Dente-de-leão', categoryId: 4 },
  { name: 'Hortelã', categoryId: 4 },
  { name: 'Manjericão', categoryId: 4 },
  { name: 'Orégano', categoryId: 4 },
  { name: 'Alecrim', categoryId: 4 },
  { name: 'Sálvia', categoryId: 4 },
  { name: 'Tomilho', categoryId: 4 },
  { name: 'Louro', categoryId: 4 },
  { name: 'Cogumelo', categoryId: 4 },
  { name: 'Shimeji', categoryId: 4 },
  { name: 'Shitake', categoryId: 4 },
  { name: 'Portobello', categoryId: 4 },
  { name: 'Pimenta dedo-de-moça', categoryId: 4 },
  { name: 'Pimenta biquinho', categoryId: 4 },
  { name: 'Pimenta cambuci', categoryId: 4 },
  { name: 'Pimenta jalapeño', categoryId: 4 },
  { name: 'Alface americana', categoryId: 4 },
  { name: 'Alface crespa', categoryId: 4 },
  { name: 'Alface roxa', categoryId: 4 },
  { name: 'Alface lisa', categoryId: 4 },
  { name: 'Rúcula selvagem', categoryId: 4 },
  { name: 'Almeirão', categoryId: 4 },
  { name: 'Catalônia', categoryId: 4 },
  { name: 'Beldroega', categoryId: 4 },
  { name: 'Capuchinha', categoryId: 4 },
  { name: 'Bertalha', categoryId: 4 },
  { name: 'Vinagreira', categoryId: 4 },
  { name: 'Peixinho', categoryId: 4 },
  { name: 'Ora-pro-nóbis', categoryId: 4 },
  { name: 'Azedinha', categoryId: 4 },
  { name: 'Caruru', categoryId: 4 },
  { name: 'Major-gomes', categoryId: 4 },
  { name: 'Picão', categoryId: 4 },
  { name: 'Serralha', categoryId: 4 },
  { name: 'Tanchagem', categoryId: 4 },
  { name: 'Tupinambo', categoryId: 4 },
  { name: 'Yacon', categoryId: 4 },
  { name: 'Araruta', categoryId: 4 },
  { name: 'Amaranto', categoryId: 4 },
  { name: 'Fava', categoryId: 4 },
  { name: 'Jambu', categoryId: 4 },
  { name: 'Cambuquira', categoryId: 4 },
  
  { name: 'Achocolatado em pó', categoryId: 5 },
  { name: 'Capuccino', categoryId: 5 },
  { name: 'Cevada solúvel', categoryId: 5 },
  { name: 'Esponja de aço', categoryId: 14 },
  { name: 'Luva de limpeza', categoryId: 8 },
  { name: 'Rodo', categoryId: 14 },
  { name: 'Vassoura', categoryId: 14 },
  { name: 'Pá de lixo', categoryId: 14 },
  { name: 'Desinfetante', categoryId: 8 },
  { name: 'Limpa vidro', categoryId: 8 },
  { name: 'Multiuso', categoryId: 8 },
  { name: 'Lustra móveis', categoryId: 8 },
  { name: 'Inseticida', categoryId: 8 },
  { name: 'Sabonete líquido', categoryId: 7 },
  { name: 'Creme dental', categoryId: 7 },
  { name: 'Fio dental', categoryId: 7 },
  { name: 'Escova de dentes', categoryId: 7 },
  { name: 'Enxaguante bucal', categoryId: 7 },
  { name: 'Escova de cabelo', categoryId: 7 },
  { name: 'Pente', categoryId: 7 },
  { name: 'Gel de cabelo', categoryId: 7 },
  { name: 'Fixador', categoryId: 7 },
  { name: 'Creme para pentear', categoryId: 7 },
  { name: 'Sabão em barra', categoryId: 8 },
  { name: 'Sabão líquido', categoryId: 8 },
  { name: 'Tira-manchas', categoryId: 8 },
  { name: 'Removedor de manchas', categoryId: 8 },
  { name: 'Alvejante', categoryId: 8 },
  { name: 'Desinfetante de banheiro', categoryId: 8 },
  { name: 'Pastilha sanitária', categoryId: 8 },
  { name: 'Limpador de vaso', categoryId: 8 },
  { name: 'Álcool gel', categoryId: 7 },
  { name: 'Desodorizador de ambiente', categoryId: 8 }, 
  { name: 'Raspador de legumes', categoryId: 14 },
  { name: 'Descascador', categoryId: 14 },
  { name: 'Ralador', categoryId: 14 },
  { name: 'Abridor de latas', categoryId: 14 },
  { name: 'Saca-rolhas', categoryId: 14 },
  { name: 'Espremedor de alho', categoryId: 14 },
  { name: 'Espremedor de frutas', categoryId: 14 },
  { name: 'Moedor de pimenta', categoryId: 14 },
  { name: 'Coador de café', categoryId: 14 },
  { name: 'Peneira', categoryId: 14 },
  { name: 'Garrafa térmica', categoryId: 14 },
  { name: 'Porta-temperos', categoryId: 14 },
  { name: 'Forma de gelo', categoryId: 14 },
  { name: 'Escorredor de louça', categoryId: 14 },
  { name: 'Luminária de emergência', categoryId: 14 },
  { name: 'Lâmina de barbear', categoryId: 7 },
  { name: 'Aparelho de barbear', categoryId: 7 },
  { name: 'Espuma de barbear', categoryId: 7 },
  { name: 'Creme pós-barba', categoryId: 7 },
  { name: 'Cotonete', categoryId: 7 },
  { name: 'Esparadrapo', categoryId: 7 },
  { name: 'Curativo adesivo', categoryId: 7 },
  { name: 'Algodão', categoryId: 7 },
  { name: 'Gaze', categoryId: 7 },
  { name: 'Soro fisiológico', categoryId: 7 },
  { name: 'Termômetro', categoryId: 7 },
  { name: 'Analgésico', categoryId: 7 },
  { name: 'Antitérmico', categoryId: 7 },
  { name: 'Antisséptico bucal', categoryId: 7 },
  { name: 'Colírio', categoryId: 7 },
  { name: 'Pilha', categoryId: 14 },
  { name: 'Fladinha', categoryId: 2 },
  { name: 'Salsinha', categoryId: 12 },
  { name: 'Removedor', categoryId: 14 },
  { name: 'Limpa alumínio', categoryId: 14 },
  { name: 'Palha de aço', categoryId: 14 },
  { name: 'Esponja louça', categoryId: 14 },
  { name: 'Fósforo', categoryId: 14 },
  { name: 'Isqueiro', categoryId: 14 },
  { name: 'Vela', categoryId: 14 },
  { name: 'Extensão elétrica', categoryId: 14 },
  { name: 'Saco de lixo', categoryId: 8 },
  { name: 'Balde', categoryId: 14 },
  { name: 'Escova sanitária', categoryId: 14 },
  { name: 'Organizador de plástico', categoryId: 14 },
  { name: 'Prendedor de roupa', categoryId: 14 },
]

