
export const categories = [
  { id: 1, name: "Grãos" },
  { id: 2, name: "Carnes" },
  { id: 3, name: "Laticínios" },
  { id: 4, name: "Hortifruti" },
  { id: 5, name: "Bebidas" },
  { id: 6, name: "Padaria" },
  { id: 7, name: "Higiene" },
  { id: 8, name: "Limpeza" },
  { id: 9, name: "Congelados" },
  { id: 10, name: "Doces" },
  { id: 11, name: "Massas" },
  { id: 12, name: "Molhos e Temperos" },
  { id: 13, name: "Pet Shop" },
  { id: 14, name: "Utilidades Domésticas" },
  { id: 15, name: "Bebê" },
  { id: 16, name: "Cereais" },
  { id: 17, name: "Snacks" },
  { id: 18, name: "Enlatados" },
  { id: 19, name: "Óleos e Gorduras" },
  { id: 20, name: "Produtos Naturais" }
];

export const items = [
  { name: 'Arroz', categoryId: 1 },
  { name: 'Feijão', categoryId: 1 },
  { name: 'Lentilha', categoryId: 1 },
  { name: 'Grão-de-bico', categoryId: 1 },
  { name: 'Ervilha', categoryId: 1 },
  { name: 'Carne bovina', categoryId: 2 },
  { name: 'Frango', categoryId: 2 },
  { name: 'Peixe', categoryId: 2 },
  { name: 'Linguiça', categoryId: 2 },
  { name: 'Presunto', categoryId: 2 },
  { name: 'Leite', categoryId: 3 },
  { name: 'Queijo', categoryId: 3 },
  { name: 'Iogurte', categoryId: 3 },
  { name: 'Manteiga', categoryId: 3 },
  { name: 'Requeijão', categoryId: 3 },
  { name: 'Banana', categoryId: 4 },
  { name: 'Maçã', categoryId: 4 },
  { name: 'Tomate', categoryId: 4 },
  { name: 'Cenoura', categoryId: 4 },
  { name: 'Alface', categoryId: 4 },
  { name: 'Abacate', categoryId: 4 },
  { name: 'Abacaxi', categoryId: 4 },
  { name: 'Acerola', categoryId: 4 },
  { name: 'Ameixa', categoryId: 4 },
  { name: 'Amora', categoryId: 4 },
  { name: 'Caju', categoryId: 4 },
  { name: 'Caqui', categoryId: 4 },
  { name: 'Carambola', categoryId: 4 },
  { name: 'Coco', categoryId: 4 },
  { name: 'Damasco', categoryId: 4 },
  { name: 'Figo', categoryId: 4 },
  { name: 'Framboesa', categoryId: 4 },
  { name: 'Goiaba', categoryId: 4 },
  { name: 'Jabuticaba', categoryId: 4 },
  { name: 'Jaca', categoryId: 4 },
  { name: 'Kiwi', categoryId: 4 },
  { name: 'Laranja', categoryId: 4 },
  { name: 'Limão', categoryId: 4 },
  { name: 'Lima', categoryId: 4 },
  { name: 'Mamão', categoryId: 4 },
  { name: 'Manga', categoryId: 4 },
  { name: 'Maracujá', categoryId: 4 },
  { name: 'Melancia', categoryId: 4 },
  { name: 'Melão', categoryId: 4 },
  { name: 'Mexerica', categoryId: 4 },
  { name: 'Morango', categoryId: 4 },
  { name: 'Nectarina', categoryId: 4 },
  { name: 'Pêra', categoryId: 4 },
  { name: 'Pêssego', categoryId: 4 },
  { name: 'Pitanga', categoryId: 4 },
  { name: 'Pitaya', categoryId: 4 },
  { name: 'Romã', categoryId: 4 },
  { name: 'Tamarindo', categoryId: 4 },
  { name: 'Tangerina', categoryId: 4 },
  { name: 'Uva', categoryId: 4 },
  { name: 'Uva passa', categoryId: 4 },
  { name: 'Acerola', categoryId: 4 },
  { name: 'Cupuaçu', categoryId: 4 },
  { name: 'Graviola', categoryId: 4 },
  { name: 'Guaraná', categoryId: 4 },
  { name: 'Pupunha', categoryId: 4 },
  { name: 'Sapoti', categoryId: 4 },
  { name: 'Seriguela', categoryId: 4 },
  { name: 'Refrigerante', categoryId: 5 },
  { name: 'Suco', categoryId: 5 },
  { name: 'Água mineral', categoryId: 5 },
  { name: 'Cerveja', categoryId: 5 },
  { name: 'Vinho', categoryId: 5 },
  { name: 'Pão francês', categoryId: 6 },
  { name: 'Pão de forma', categoryId: 6 },
  { name: 'Bolo', categoryId: 6 },
  { name: 'Croissant', categoryId: 6 },
  { name: 'Torrada', categoryId: 6 },
  { name: 'Sabonete', categoryId: 7 },
  { name: 'Shampoo', categoryId: 7 },
  { name: 'Condicionador', categoryId: 7 },
  { name: 'Pasta de dente', categoryId: 7 },
  { name: 'Desodorante', categoryId: 7 },
  { name: 'Detergente', categoryId: 8 },
  { name: 'Sabão em pó', categoryId: 8 },
  { name: 'Amaciante', categoryId: 8 },
  { name: 'Água sanitária', categoryId: 8 },
  { name: 'Esponja', categoryId: 8 },
  { name: 'Pizza congelada', categoryId: 9 },
  { name: 'Lasanha congelada', categoryId: 9 },
  { name: 'Legumes congelados', categoryId: 9 },
  { name: 'Frango empanado', categoryId: 9 },
  { name: 'Sorvete', categoryId: 9 },
  { name: 'Chocolate', categoryId: 10 },
  { name: 'Bala', categoryId: 10 },
  { name: 'Biscoito recheado', categoryId: 10 },
  { name: 'Goiabada', categoryId: 10 },
  { name: 'Doce de leite', categoryId: 10 },
  { name: 'Macarrão', categoryId: 11 },
  { name: 'Lasanha', categoryId: 11 },
  { name: 'Espaguete', categoryId: 11 },
  { name: 'Talharim', categoryId: 11 },
  { name: 'Nhoque', categoryId: 11 },
  { name: 'Molho de tomate', categoryId: 12 },
  { name: 'Ketchup', categoryId: 12 },
  { name: 'Mostarda', categoryId: 12 },
  { name: 'Maionese', categoryId: 12 },
  { name: 'Sal', categoryId: 12 },
  { name: 'Ração para cachorro', categoryId: 13 },
  { name: 'Ração para gato', categoryId: 13 },
  { name: 'Areia sanitária', categoryId: 13 },
  { name: 'Petisco para cachorro', categoryId: 13 },
  { name: 'Coleira', categoryId: 13 },
  { name: 'Papel alumínio', categoryId: 14 },
  { name: 'Papel manteiga', categoryId: 14 },
  { name: 'Saco plástico', categoryId: 14 },
  { name: 'Filtro de café', categoryId: 14 },
  { name: 'Vasilha plástica', categoryId: 14 },
  { name: 'Fralda descartável', categoryId: 15 },
  { name: 'Lenço umedecido', categoryId: 15 },
  { name: 'Pomada para assaduras', categoryId: 15 },
  { name: 'Mamadeira', categoryId: 15 },
  { name: 'Chupeta', categoryId: 15 },
  { name: 'Cereal matinal', categoryId: 16 },
  { name: 'Aveia', categoryId: 16 },
  { name: 'Granola', categoryId: 16 },
  { name: 'Farinha de milho', categoryId: 16 },
  { name: 'Mingau', categoryId: 16 },
  { name: 'Batata chips', categoryId: 17 },
  { name: 'Amendoim', categoryId: 17 },
  { name: 'Pipoca', categoryId: 17 },
  { name: 'Torradinha', categoryId: 17 },
  { name: 'Biscoito salgado', categoryId: 17 },
  { name: 'Milho verde enlatado', categoryId: 18 },
  { name: 'Ervilha enlatada', categoryId: 18 },
  { name: 'Atum enlatado', categoryId: 18 },
  { name: 'Sardinha enlatada', categoryId: 18 },
  { name: 'Molho pronto enlatado', categoryId: 18 },
  { name: 'Óleo de soja', categoryId: 19 },
  { name: 'Azeite de oliva', categoryId: 19 },
  { name: 'Óleo de girassol', categoryId: 19 },
  { name: 'Banha', categoryId: 19 },
  { name: 'Margarina', categoryId: 19 },
  { name: 'Castanha-do-pará', categoryId: 20 },
  { name: 'Castanha de caju', categoryId: 20 },
  { name: 'Nozes', categoryId: 20 },
  { name: 'Amêndoas', categoryId: 20 },
  { name: 'Sementes de chia', categoryId: 20 },
  { name: 'Sementes de linhaça', categoryId: 20 },
  { name: 'Papel higiênico', categoryId: 7 },
  { name: 'Papel toalha', categoryId: 7 },
  { name: 'Guardanapo', categoryId: 7 },
  { name: 'Lenço de papel', categoryId: 7 },
  { name: 'Absorvente', categoryId: 7 },
  { name: 'Vinagre', categoryId: 12 },
  { name: 'Molho shoyu', categoryId: 12 },
  { name: 'Molho inglês', categoryId: 12 },
  { name: 'Pimenta', categoryId: 12 },
  { name: 'Tempero pronto', categoryId: 12 },
  { name: 'Farinha de trigo', categoryId: 1 },
  { name: 'Açúcar', categoryId: 1 },
  { name: 'Fermento químico', categoryId: 1 },
  { name: 'Chocolate em pó', categoryId: 10 },
  { name: 'Leite condensado', categoryId: 10 },
  { name: 'Café', categoryId: 5 },
  { name: 'Chá', categoryId: 5 },
  { name: 'Abóbora', categoryId: 4 },
  { name: 'Abobrinha', categoryId: 4 },
  { name: 'Agrião', categoryId: 4 },
  { name: 'Aipo', categoryId: 4 },
  { name: 'Alcachofra', categoryId: 4 },
  { name: 'Alho', categoryId: 4 },
  { name: 'Alho-poró', categoryId: 4 },
  { name: 'Aspargo', categoryId: 4 },
  { name: 'Batata', categoryId: 4 },
  { name: 'Batata-doce', categoryId: 4 },
  { name: 'Batata-baroa', categoryId: 4 },
  { name: 'Berinjela', categoryId: 4 },
  { name: 'Beterraba', categoryId: 4 },
  { name: 'Brócolis', categoryId: 4 },
  { name: 'Cebola', categoryId: 4 },
  { name: 'Cebolinha', categoryId: 4 },
  { name: 'Chicória', categoryId: 4 },
  { name: 'Coentro', categoryId: 4 },
  { name: 'Couve', categoryId: 4 },
  { name: 'Couve-flor', categoryId: 4 },
  { name: 'Couve-de-bruxelas', categoryId: 4 },
  { name: 'Espinafre', categoryId: 4 },
  { name: 'Erva-doce', categoryId: 4 },
  { name: 'Escarola', categoryId: 4 },
  { name: 'Funcho', categoryId: 4 },
  { name: 'Gengibre', categoryId: 4 },
  { name: 'Inhame', categoryId: 4 },
  { name: 'Jiló', categoryId: 4 },
  { name: 'Maxixe', categoryId: 4 },
  { name: 'Mostarda', categoryId: 4 },
  { name: 'Nabo', categoryId: 4 },
  { name: 'Palmito', categoryId: 4 },
  { name: 'Pepino', categoryId: 4 },
  { name: 'Pimentão', categoryId: 4 },
  { name: 'Quiabo', categoryId: 4 },
  { name: 'Rabanete', categoryId: 4 },
  { name: 'Repolho', categoryId: 4 },
  { name: 'Rúcula', categoryId: 4 },
  { name: 'Salsa', categoryId: 4 },
  { name: 'Taioba', categoryId: 4 },
  { name: 'Vagem', categoryId: 4 },
  { name: 'Xuxu', categoryId: 4 },
  { name: 'Mandioquinha', categoryId: 4 },
  { name: 'Bardana', categoryId: 4 },
  { name: 'Cará', categoryId: 4 },
  { name: 'Chuchu', categoryId: 4 },
  { name: 'Dente-de-leão', categoryId: 4 },
  { name: 'Hortelã', categoryId: 4 },
  { name: 'Manjericão', categoryId: 4 },
  { name: 'Orégano', categoryId: 4 },
  { name: 'Alecrim', categoryId: 4 },
  { name: 'Sálvia', categoryId: 4 },
  { name: 'Tomilho', categoryId: 4 },
  { name: 'Louro', categoryId: 4 },
  { name: 'Cogumelo', categoryId: 4 },
  { name: 'Shimeji', categoryId: 4 },
  { name: 'Shitake', categoryId: 4 },
  { name: 'Portobello', categoryId: 4 },
  { name: 'Pimenta dedo-de-moça', categoryId: 4 },
  { name: 'Pimenta biquinho', categoryId: 4 },
  { name: 'Pimenta cambuci', categoryId: 4 },
  { name: 'Pimenta jalapeño', categoryId: 4 },
  { name: 'Alface americana', categoryId: 4 },
  { name: 'Alface crespa', categoryId: 4 },
  { name: 'Alface roxa', categoryId: 4 },
  { name: 'Alface lisa', categoryId: 4 },
  { name: 'Rúcula selvagem', categoryId: 4 },
  { name: 'Almeirão', categoryId: 4 },
  { name: 'Catalônia', categoryId: 4 },
  { name: 'Beldroega', categoryId: 4 },
  { name: 'Capuchinha', categoryId: 4 },
  { name: 'Bertalha', categoryId: 4 },
  { name: 'Vinagreira', categoryId: 4 },
  { name: 'Peixinho', categoryId: 4 },
  { name: 'Ora-pro-nóbis', categoryId: 4 },
  { name: 'Azedinha', categoryId: 4 },
  { name: 'Caruru', categoryId: 4 },
  { name: 'Major-gomes', categoryId: 4 },
  { name: 'Picão', categoryId: 4 },
  { name: 'Serralha', categoryId: 4 },
  { name: 'Tanchagem', categoryId: 4 },
  { name: 'Tupinambo', categoryId: 4 },
  { name: 'Yacon', categoryId: 4 },
  { name: 'Araruta', categoryId: 4 },
  { name: 'Amaranto', categoryId: 4 },
  { name: 'Fava', categoryId: 4 },
  { name: 'Jambu', categoryId: 4 },
  { name: 'Cambuquira', categoryId: 4 },
  { name: 'Achocolatado em pó', categoryId: 5 },
  { name: 'Capuccino', categoryId: 5 },
  { name: 'Cevada solúvel', categoryId: 5 },
  { name: 'Esponja de aço', categoryId: 14 },
  { name: 'Luva de limpeza', categoryId: 8 },
  { name: 'Rodo', categoryId: 14 },
  { name: 'Vassoura', categoryId: 14 },
  { name: 'Pá de lixo', categoryId: 14 },
  { name: 'Desinfetante', categoryId: 8 },
  { name: 'Limpa vidro', categoryId: 8 },
  { name: 'Multiuso', categoryId: 8 },
  { name: 'Lustra móveis', categoryId: 8 },
  { name: 'Inseticida', categoryId: 8 },
  { name: 'Sabonete líquido', categoryId: 7 },
  { name: 'Creme dental', categoryId: 7 },
  { name: 'Fio dental', categoryId: 7 },
  { name: 'Escova de dentes', categoryId: 7 },
  { name: 'Enxaguante bucal', categoryId: 7 },
  { name: 'Escova de cabelo', categoryId: 7 },
  { name: 'Pente', categoryId: 7 },
  { name: 'Gel de cabelo', categoryId: 7 },
  { name: 'Fixador', categoryId: 7 },
  { name: 'Creme para pentear', categoryId: 7 },
  { name: 'Sabão em barra', categoryId: 8 },
  { name: 'Sabão líquido', categoryId: 8 },
  { name: 'Tira-manchas', categoryId: 8 },
  { name: 'Removedor de manchas', categoryId: 8 },
  { name: 'Alvejante', categoryId: 8 },
  { name: 'Desinfetante de banheiro', categoryId: 8 },
  { name: 'Pastilha sanitária', categoryId: 8 },
  { name: 'Limpador de vaso', categoryId: 8 },
  { name: 'Álcool gel', categoryId: 7 },
  { name: 'Desodorizador de ambiente', categoryId: 8 }, 
  { name: 'Raspador de legumes', categoryId: 14 },
  { name: 'Descascador', categoryId: 14 },
  { name: 'Ralador', categoryId: 14 },
  { name: 'Abridor de latas', categoryId: 14 },
  { name: 'Saca-rolhas', categoryId: 14 },
  { name: 'Espremedor de alho', categoryId: 14 },
  { name: 'Espremedor de frutas', categoryId: 14 },
  { name: 'Moedor de pimenta', categoryId: 14 },
  { name: 'Coador de café', categoryId: 14 },
  { name: 'Peneira', categoryId: 14 },
  { name: 'Lâmina de barbear', categoryId: 7 },
  { name: 'Aparelho de barbear', categoryId: 7 },
  { name: 'Espuma de barbear', categoryId: 7 },
  { name: 'Creme pós-barba', categoryId: 7 },
  { name: 'Cotonete', categoryId: 7 },
  { name: 'Esparadrapo', categoryId: 7 },
  { name: 'Curativo adesivo', categoryId: 7 },
  { name: 'Algodão', categoryId: 7 },
  { name: 'Gaze', categoryId: 7 },
  { name: 'Soro fisiológico', categoryId: 7 },
  { name: 'Termômetro', categoryId: 7 },
  { name: 'Analgésico', categoryId: 7 },
  { name: 'Antitérmico', categoryId: 7 },
  { name: 'Antisséptico bucal', categoryId: 7 },
  { name: 'Colírio', categoryId: 7 },
  { name: 'Pilha', categoryId: 14 },
  { name: 'Fósforo', categoryId: 14 },
  { name: 'Isqueiro', categoryId: 14 },
  { name: 'Vela', categoryId: 14 },
  { name: 'Extensão elétrica', categoryId: 14 },
  { name: 'Saco de lixo', categoryId: 8 },
  { name: 'Balde', categoryId: 14 },
  { name: 'Escova sanitária', categoryId: 14 },
  { name: 'Organizador de plástico', categoryId: 14 },
  { name: 'Prendedor de roupa', categoryId: 14 },
]

